labels:
  - name: "simple :thinking:"
    color: "#F2C5E0"
    conditions:
      - maxLines: 100
  - name: "normal :thinking:"
    color: "#EC8FD0"
    conditions:
      - minLines: 100
      - maxLines: 500
  - name: "complex :thinking:"
    color: "#D43790"
    conditions:
      - maxLines: 2000
      - minLines: 500
  - name: "headache :thinking:"
    color: "#AE388B"
    conditions:
      - minLines: 2000
  - name: "important ⚠️"
    conditions:
      - title: "/^hotfix\\/[a-z0-9\\-_ &#$@!?%]+$/i"
      - minLines: 500
  - name: "important ⚠️"
    conditions:
      - body: "/#important/gmi"
  - name: "wip :construction:"
    conditions:
      - body: "/#(wip|work in progress|work_in_progress|work-in-progress)/gmi"
  - name: "feature :rocket:"
    conditions:
      - title: "/^feat(ure)?\\/[a-z0-9\\-_ &#$@!?%]+$/i"
  - name: "fix :wrench:"
    conditions:
      - title: "/^fix\\/[a-z0-9\\-_ &#$@!?%]+$/i"
  - name: "hotfix :fire_engine:"
    conditions:
      - title: "/^hotfix\\/[a-z0-9\\-_ &#$@!?%]+$/i"
  - name: "poc :thought_balloon:"
    conditions:
      - title: "/^(poc|test)\\/[a-z0-9\\-_ &#$@!?%]+$/i"
  - name: "small :file_folder:"
    conditions:
      - maxFiles: 10
  - name: "medium :file_folder:"
    conditions:
      - maxFiles: 25
      - minFiles: 10
  - name: "large :file_folder:"
    conditions:
      - maxFiles: 50
      - minFiles: 25
  - name: "titanic :file_folder:"
    conditions:
      - minFiles: 50
  - name: "JS/TS"
    conditions:
      - files: ["**/*.js", "**/*.ts"]
  - name: "Ready! :white_check_mark:"
    conditions:
      - mergeable: true
