import {info} from '@actions/core'
import {Label, LabelType, LogicalLabel} from '../types'

const parseLabel = (formattedString: string): Label => {
  const key = formattedString.split('=')[0]
  const [name, color] = key.split('|')
  return {
    name,
    description: `PR-Labeler autogenerated ${name} label`,
    color
  } as Label
}

const parseLogicalLabel = (
  formattedString: string,
  labelType: LabelType
): LogicalLabel => {
  const [key, condition] = formattedString.split('=')
  const [name, color] = key.split('|')
  const description = `PR-Labeler autogenerated ${name} label`
  return new LogicalLabel(
    name,
    color,
    description,
    labelType === LabelType.SIZE && condition.length === 0
      ? Number.MAX_SAFE_INTEGER.toString()
      : condition,
    labelType
  )
}

export const parseLabels = (formattedString: string): Label[] => {
  return formattedString.split(',').map(v => parseLabel(v))
}

const parseLogicalLabelsFromFormattedString = (
  formattedString: string,
  labelType: LabelType
): LogicalLabel[] => {
  return formattedString.split(',').map(v => parseLogicalLabel(v, labelType))
}

const labelRegexMatch = (scanTarget: string, label: LogicalLabel): boolean => {
  const condition: string =
    new RegExp(/(?<=\/).*(?=\/)/).exec(label.condition)?.[0] || ''
  const flags: string | undefined = new RegExp(/\/.{0,3}$/)
    .exec(label.condition)?.[0]
    .replace('/', '')
  info(`testing with condition: ${condition} and flags: ${flags}`)
  const regExpFromLabel: RegExp = flags
    ? new RegExp(condition, flags)
    : new RegExp(condition)
  return regExpFromLabel.test(scanTarget)
}

export const getLabelForChangeSize = (
  changeSize: number,
  sizeLabels: string
): Label => {
  const possibleLabels: LogicalLabel[] = parseLogicalLabelsFromFormattedString(
    sizeLabels,
    LabelType.SIZE
  )
  possibleLabels.sort((a, b) => parseInt(a.condition) - parseInt(b.condition))
  for (const label of possibleLabels) {
    if (parseInt(label.condition) > changeSize) {
      return label
    }
  }
  throw new Error(`Unexpected error while retrieving label for pull request.`)
}

export const isLabelPresent = (
  label: {name: string},
  labels: {name: string}[]
): boolean => {
  const sameName = (labelA: {name: string}, labelB: {name: string}): boolean =>
    labelA.name.trim().toLocaleLowerCase() ===
    labelB.name.trim().toLocaleLowerCase()
  return !!labels.find(labelInArray => sameName(labelInArray, label))
}

export const getPossibleRegularExpressionLabels = (
  regularExpressionLabels: string
): LogicalLabel[] => {
  const logicalLabels: LogicalLabel[] = parseLogicalLabelsFromFormattedString(
    regularExpressionLabels,
    LabelType.REGEX
  )
  return logicalLabels
}

const logLabel = (label: LogicalLabel): void =>
  info(
    `label: ${label.name}, color: ${label.color}, condition: ${label.condition}`
  )
const logLabels = (labels: LogicalLabel[]): void => {
  for (const label of labels) {
    logLabel(label)
  }
}

export const getMatchingRegularExpressionLabels = (
  scanTarget: string,
  possibleLabels: LogicalLabel[]
): Label[] => {
  logLabels(possibleLabels)
  const matchingLabels: Label[] = []
  for (const label of possibleLabels) {
    if (labelRegexMatch(scanTarget, label)) {
      info('match found!')
      logLabel(label)
      matchingLabels.push(label)
    }
  }
  return matchingLabels
}
