name: 'Auto Merger'

on:
  schedule:
    - cron: '2 * * * *'
jobs:
  if_status_passed_and_dependabot:
  # this action approves the pull request when status passed and the author is dependabot
    runs-on: ubuntu-latest
    steps:
      - run: export OWNER=$(gh repo view --json owner --jq '.owner.login')
      - run: export REPO=$(gh repo view --json name --jq '.name')
      - run: echo "$OWNER and $REPO"
        #gh api repos/prulloac/configurable-pr-labeler/pulls --jq '.[] | select(.head.ref | contains("dependabot")) | .number'
#      - run: gh api repos/$()/$()/pulls --jq '.[] | select(.head.ref | contains("dependabot")) | .number' > prs.txt
