name: 'PR Labeler'
on: # rebuild any PRs and main branch changes
  pull_request:
    types:
      [opened, reopened, edited, synchronize]
    branches:
      - main
      - 'development'

jobs:
  label: # name of the job. Jobs run in parallel unless specified otherwise.
    name: "Label PR"
    permissions:
      pull-requests: write
      issues: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: prulloac/configurable-pr-labeler@v1.0.1
        with:
          token: ${{secrets.GITHUB_TOKEN}}
