name: 'PR Labeler'
on: # rebuild any PRs and main branch changes
  pull_request:
    types:
      [opened, reopened, edited, synchronize]
    branches:
      - main
      - 'development'

jobs:
  label: # name of the job. Jobs run in parallel unless specified otherwise.
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: prulloac/pr-labeler@main
        with:
          token: ${{secrets.GITHUB_TOKEN}}
